on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Go environment
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
      - name: Show directory
        run: |
          pwd
          ls -A
      - name: Build Go binary
        working-directory: ../prometheus
        run: |
          go mod download
          go build -o prometheus .
      # Set up Docker Buildx for multi-platform builds (optional but recommended)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      # Build and push the Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/prometheus:latest
          file: ./Dockerfile
      # Optionally verify the image was pushed correctly
      - name: Verify Docker image
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/prometheus:latest
          docker images
